[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "meal-generator"
version = "1.0.0"
dependencies = [
    "google-genai",
]

[tool.setuptools.packages.find]
where = ["src"]